### ISSUE TITLE
Move from manage_externals to submodules

### ISSUE THREAD

**Issue by AndrewJConley** [NCAR/MusicBox#71]
TUV_rt should become its own repository and part of a different suite.  Then each of the suites (perhaps schemes) should become their own submodule.

**Comment by fvitt** [comment]
What is the motivation to submodules rather than manage_externals?  In my limited experience I found submodules difficult to understand and work with.  I am more comfortable with manage_externals.

**Comment by AndrewJConley** [comment]
Testing and committing with manage_externals requires a commit of the
subsidiary code, then a change to the "Externals" file and then a commit of
the Host code, and only then can I check that the whole thing checks out
and compiles.  This means that I can end up with non-functioning code that
is committed.

Submodules is a standard tool used by the rest of the software development
community.  It is a bit tricky to learn at first, but solve a number of
these issues.

**Comment by gold2718** [comment]
Your description of using manage_externals is hardly different from working with submodules. After updating the submodule repository, you have to update the parent repo with the new hash. Note that the new hash is hidden (not in the .gitmodules file) unlike in manage_externals.
The 'extra step' in manage_externals is to explicitly add the new hash or tag to the externals file. This provides documentation as to the intent of the update.
For instance, you could do:
```
git show old_tag:Externals.cfg
```
to see what sub-repository tags were used. I do not know of the equivalent for submodules.
You mentioned 'a number of these issues' with manage_externals. Could you please list them?

You also mentioned git submodule use in the software development community. On the other hand, manage_externals is gaining a lot of traction in the modeling community (e.g., in the new NOAA models).

**Comment by mattldawson** [comment]
I think the command for this with sub-modules is:
```
git ls-tree old_tag folder/submodule/is/in/
```
I ran into difficulty when I was working on an update that involved changes in MICM and MusicBox. I wanted to build and run the code following the Docker instructions before I committed anything, but I couldn't figure out how to do this with manage_externals (although I am very new to manage_externals). I ended up committing the MICM code, changing the Externals.cfg and then building the model and debugging.

**Comment by gold2718** [comment]
Does `git ls-tree` show you the tag or just the hash?

I am confused about your docker problem description. If you did not commit anything then the docker build and test could not have checked out anything, right? If not right, what am I missing?
If you were just building and running an existing sandbox, how is manage_externals (or submodules) relevant?

**Comment by mattldawson** [comment]
It shows the hash. But, one of the nice things about sub-modules is that you rarely have to work directly with this information. Over the last two years I worked daily with a repo that had multiple sub-modules and sub-modules within sub-modules, and I never once needed to use this command.

The way Docker is set up for MusicBox is that it copies your local MusicBox repo (including any uncommitted changes) and during the build, Docker runs the checkout_externals script. So a new user would just run:
```
git clone https://github.com/NCAR/MusicBox.git
docker build -t music-box . --build-arg TAG=272
docker run -it music-box bash
```
Uncommitted changes in your local MusicBox repo would be copied to the container, but the externals are checked out by Docker.

With sub-modules, this would be:
```
git clone --recurse-submodules https://github.com/NCAR/MusicBox.git
docker build -t music-box . --build-arg TAG=272
docker run -it music-box bash
```

If you had any uncommitted changes in the parent repo or any recursed submodules, they would be copied to the container before the build.

**Comment by mattldawson** [comment]
Another nice feature is that if you're looking at the repo in a browser, the submodules appear in the file tree as a folder with the hash they point to printed next to the folder, and are hyperlinked to that commit in the child repo.

![image](https://user-images.githubusercontent.com/13121557/85637639-960bc900-b638-11ea-8d3a-874133a8a734.png)

**Comment by gold2718** [comment]
> It shows the hash. But, one of the nice things about sub-modules is that you rarely have to work directly with this information. 

The tags are required for model provenance. This is a science requirement, not a software engineering requirement. This is one of the reasons we created the tool and made sure that the necessary information is in easily-accessible text form.

I am still confused by your docker issue. In your example, how are 'uncommited changes' copied when you only provide a github URL? How does docker know the magic location where it should find uncommitted changes?

**Comment by gold2718** [comment]
> Another nice feature is that if you're looking at the repo in a browser, the submodules appear in the file tree as a folder with the hash they point to printed next to the folder, and are hyperlinked to that commit in the child repo.

This is a relatively new GitHub (not git) feature. I agree that the link to the subrepo is nice (again, for software engineers, not so much for scientists).

**Comment by mattldawson** [comment]
> The tags are required for model provenance.

Submodules don't prevent you from tagging your code. And you can easily checkout a tagged commit in a submodule. If you want to make it easy for scientists to see what tag, if any, a submodule is associated with, you could include a very simple script in the parent repo that they could run that would show this information for all the submodules.

> How does docker know the magic location where it should find uncommitted changes?

They are on your local machine. Docker does not git clone the model. If you do this:
```
git clone --recurse-submodules https://github.com/NCAR/MusicBox.git
```
...and then make changes to MusicBox (parent) or MICM (submodule) in your local cloned repo, when you run this:
```
docker build -t music-box . --build-arg TAG=272
```
...Docker copies your local repo, with the submodules and all the changes you've made into the container and then does the build. It matters where you call this from, I should have mentioned that you must be in the root MusicBox folder where the Dockerfile is when you run `docker build`.

**Comment by gold2718** [comment]
> ...Docker copies your local repo,  ...

Okay, then what is different about the manage_externals version? If you are cloning a repo, you should run ./manage_externals/checkout_externals but not if you are copying an existing repo. I still have no idea what caused the manage_externals version to fail. Please fill me in.

**Comment by mattldawson** [comment]
For the manage externals version, I run:
```
git clone https://github.com/NCAR/MusicBox.git
```
I can make changes to the MusicBox code, which will make it to the container. But, when I run:
```
docker build -t music-box . --build-arg TAG=272
```
... during the Docker build process, it runs `checkout_externals`, which gets MICM, etc from GitHub.

**Comment by gold2718** [comment]
Let me see if I understand what you are trying to support.
True or False: the docker build does _not_ run git commands.

Assuming that the statement above is True, that means to me that the docker build is assuming that the user has set up a sandbox to build and test.

What happens if the user says:
```
git clone https://github.com/NCAR/MusicBox.git
```
and forgets the `--recurse-submodules`?

**Comment by AndrewJConley** [comment]
If you are developing the “host” model and unaware that the rest of the model isn’t there, you could do the following to collect the other repositories.
>cd cloned-repo
>git submodule update —init —recursive

But I wonder how you are developing the host model without running tests.

Andrew

**Comment by gold2718** [comment]
@AndrewJConley, everything you say applies equally to manage_externals, it is just a different command (one used increasingly often by the modeling community to whom you will be marketing MICM).
> But I wonder how you are developing the host model without running tests.

Exactly! Except for unit tests (which may or may not need docker), it sounds like you are saying that the user should be responsible for setting up a sandbox before calling `docker build`. I agree.

**Comment by AndrewJConley** [comment]
What about unit tests that do not need the host model?  Are they not supposed to use standard development tools (i.e., git)?

Andrew

**Comment by gold2718** [comment]
> What about unit tests that do not need the host model?  Are they not supposed to use standard development tools (i.e., git)?

I suppose that depends on your definition of "unit test", I am unaware of any standard definition (and have been reading various definitions for decades).
That being said, I do not see how your comment is relevant here because if you are running unit tests 'that do not need the host model', I assume you are talking about MICM, not MusicBox. What am I missing?

**Comment by mattldawson** [comment]
@gold2718 - I think I understand what you're saying, let me know if this is correct. With manage externals, a user who is not interested in modifying the code would run:
```
git clone https://github.com/NCAR/MusicBox.git
cd MusicBox
./manage_externals/checkout_externals
docker build -t music-box . --build-arg TAG=272
docker run -it music-box bash
```
instead of:
```
git clone --recurse-submodules https://github.com/NCAR/MusicBox.git
docker build -t music-box MusicBox/. --build-arg TAG=272
docker run -it music-box bash
```

... and that a developer that is modifying MICM and MusicBox code would run
```
git clone https://github.com/NCAR/MusicBox.git
cd MusicBox
./manage_externals/checkout_externals
rm -fr MICM_chemistry
git clone https://github.com/NCAR/MICM_chemistry.git
git checkout [tag from Externals.cfg]
< do edits >
docker build -t music-box . --build-arg TAG=272
docker run -it music-box bash
```
instead of:
```
git clone --recurse-submodules https://github.com/NCAR/MusicBox.git
< do edits >
docker build -t music-box MusicBox/. --build-arg TAG=272
docker run -it music-box bash
```

If this is correct, I can see how it could work (the Dockerfile would need modified to remove the call to `checkout_externals`).

I'm happy to go along with whatever is decided, but my personal vote would still be for submodules because:
- it's a native git feature
- it requires fewer steps for both users and developers
- it's still not clear to me what manage externals does that submodules doesn't do

I yield the floor.

**Comment by gold2718** [comment]
@mattldawson, I do not understand this bit:
```
rm -fr MICM_chemistry
git clone https://github.com/NCAR/MICM_chemistry.git
git checkout [tag from Externals.cfg]
```
Why do that? Why not just do
```
git clone https://github.com/NCAR/MusicBox.git
cd MusicBox
./manage_externals/checkout_externals
cd MICM_chemistry
< do edits >
docker build -t music-box . --build-arg TAG=272
docker run -it music-box bash
```
What I usually do is to checkout a new branch just before the `< do edits >` step but otherwise, it is a normal workflow. manage_externals does a full clone while git submodules does a shallow clone (at least by default).

I often end up with an extensive workflow in the subproject with multiple remotes etc. For instance, I do CCPP Framework development as a subproject of a host model so I can do both unit tests and system tests.

**Comment by mattldawson** [comment]
> Why do that? Why not just do

Yes, my mistake
