### ISSUE TITLE
build and run without docker

### ISSUE THREAD

**Issue by fvitt** [NCAR/MusicBox#74]
Can we have instructions on how to build and run MusicBox without docker?

I don't see the advantage of using docker on modeling2 where docker is not installed

**Comment by AndrewJConley** [comment]
There are now instructions in the wiki: https://wiki.ucar.edu/display/MusicBox/Running+MusicBox+on+Modeling2.acom.ucar.edu

**Comment by fvitt** [comment]
get_tag.py gives errors:

modeling2:/terminator-data1/home/fvitt/micmdev/MusicBox/Mechanism_collection> python3 get_tag.py -tag_id 272
www.acom.ucar.edu
/cgi-bin/acd/mechanism.py?hash=272
Traceback (most recent call last):
  File "get_tag.py", line 108, in <module>
    mech_json = json.loads(mechanism)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
modeling2:/terminator-data1/home/fvitt/micmdev/MusicBox/Mechanism_collection> 
modeling2:/terminator-data1/home/fvitt/micmdev/MusicBox/Mechanism_collection> 
modeling2:/terminator-data1/home/fvitt/micmdev/MusicBox/Mechanism_collection> 
modeling2:/terminator-data1/home/fvitt/micmdev/MusicBox/Mechanism_collection> python3 get_tag.py -tag_id 274
www.acom.ucar.edu
/cgi-bin/acd/mechanism.py?hash=274
Traceback (most recent call last):
  File "get_tag.py", line 108, in <module>
    mech_json = json.loads(mechanism)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by AndrewJConley** [comment]
This is an issue with the NCAR web servers.  But it does also show an issue with the error message from the get_tag python script.
Andrew: improve the error message for timeout of the tag collector.
Carl: Make the web service more reliable.

**Comment by AndrewJConley** [comment]
@fvitt  As a stop-gap measure you can copy modeling1:/home/aconley/mechanism_store/mechanisms/274.json into Mechanism_collection/configured_tags/274/

**Comment by mattldawson** [comment]
Hi @AndrewJConley and @fvitt,

This is not related to `get_tag.py` and is pretty minor, but I notice in the wiki instructions under "Preprocessor," it says "if you want your own local copy," but this step is not optional if you follow this instruction in "Get some tag of some mechanism":
```
> python3 preprocess_tag.py -mechanism_source_path configured_tags/$TAG_ID -preprocessor localhost:3000 
```
because the localhost:3000 preprocessor is specified.

**Comment by AndrewJConley** [comment]
I hope this is all working now.  Please continue to share issues that you may have in your particular environment.

**Comment by fvitt** [comment]
Still having issues on modeling2.  Have you tried to build and run the
latest MusicBox on modeling2?  Should I give up on modeling2 and try on my
local laptop?

**Comment by AndrewJConley** [comment]
It looks like acom web services are still down.  So you can get the tag with the following:

python3 get_tag.py -tag_id 274 -tag_server cafe-devel

If you want 272 you will need to rm -rf configured_tags/272 before collecting it.  This is an actual bug that I need to fix.
