### ISSUE TITLE
Define sources of inputs for MusicBox 

### ISSUE THREAD

**Issue by marybarthbrock** [NCAR/MusicBox#77]
I think we should discuss what various sources (WACCM, WRF-Chem, existing BOXMOX inputs, field data) to develop a tool for MusicBox input format.

**Comment by AndrewJConley** [comment]
Matt has presented a [requirements document](https://docs.google.com/document/d/1z0-_vGF6JcT9NSzweswp33MXjOCDG4_Wsa9hYF983_U/edit?usp=sharing), and elaborated with a potential user [interface description](https://docs.google.com/document/d/1Bz_IcbMar-pRDObVjXRCo3fwdzKrAgoM1UZ2j4AeOmI/edit?usp=sharing) for various uses.  I will close this issue as the discussion has taken place and opportunities for input have been given.
