### ISSUE TITLE
Separate initial conditions and time-evolving conditions input files

### ISSUE THREAD

**Issue by fvitt** [NCAR/MusicBox#85]
MusicBox needs the ability to read initial conditions and time-evolving conditions from separate input files. 

Does MusicBox need to be backwards compatible with older env conditions files?  That is, maintain the ability to read the older input files.

**Comment by AndrewJConley** [comment]
It doesn't need to be backward compatible, but if it is not, we will still
need to be able to run T1mozcart.

**Comment by fvitt** [comment]
The initial conditions files generated by WACCM have constituent mass mixing ratios.  I assume those need to be converted to volume mixing ratios?  Correct?  Or are we working with number densities now?   Or some other units?

**Comment by AndrewJConley** [comment]
MusicBox1.0 uses vmr.  

MusicBox2.0 will use mks units.  (Moles/m^3)

Andrew
